/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProjetosProgramacaoRouteImport } from './routes/projetos-programacao'
import { Route as ProjetosEngenhariaRouteImport } from './routes/projetos-engenharia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademicoRouteImport } from './routes/academico'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProgramacaoRoute = ProjetosProgramacaoRouteImport.update({
  id: '/projetos-programacao',
  path: '/projetos-programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosEngenhariaRoute = ProjetosEngenhariaRouteImport.update({
  id: '/projetos-engenharia',
  path: '/projetos-engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicoRoute = AcademicoRouteImport.update({
  id: '/academico',
  path: '/academico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academico': typeof AcademicoRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/contato': typeof ContatoRoute
  '/projetos-engenharia': typeof ProjetosEngenhariaRoute
  '/projetos-programacao': typeof ProjetosProgramacaoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academico': typeof AcademicoRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/contato': typeof ContatoRoute
  '/projetos-engenharia': typeof ProjetosEngenhariaRoute
  '/projetos-programacao': typeof ProjetosProgramacaoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academico': typeof AcademicoRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/contato': typeof ContatoRoute
  '/projetos-engenharia': typeof ProjetosEngenhariaRoute
  '/projetos-programacao': typeof ProjetosProgramacaoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academico'
    | '/auth'
    | '/calculadoras'
    | '/contato'
    | '/projetos-engenharia'
    | '/projetos-programacao'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academico'
    | '/auth'
    | '/calculadoras'
    | '/contato'
    | '/projetos-engenharia'
    | '/projetos-programacao'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academico'
    | '/auth'
    | '/calculadoras'
    | '/contato'
    | '/projetos-engenharia'
    | '/projetos-programacao'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademicoRoute: typeof AcademicoRoute
  AuthRoute: typeof AuthRoute
  CalculadorasRoute: typeof CalculadorasRoute
  ContatoRoute: typeof ContatoRoute
  ProjetosEngenhariaRoute: typeof ProjetosEngenhariaRoute
  ProjetosProgramacaoRoute: typeof ProjetosProgramacaoRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos-programacao': {
      id: '/projetos-programacao'
      path: '/projetos-programacao'
      fullPath: '/projetos-programacao'
      preLoaderRoute: typeof ProjetosProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos-engenharia': {
      id: '/projetos-engenharia'
      path: '/projetos-engenharia'
      fullPath: '/projetos-engenharia'
      preLoaderRoute: typeof ProjetosEngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academico': {
      id: '/academico'
      path: '/academico'
      fullPath: '/academico'
      preLoaderRoute: typeof AcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademicoRoute: AcademicoRoute,
  AuthRoute: AuthRoute,
  CalculadorasRoute: CalculadorasRoute,
  ContatoRoute: ContatoRoute,
  ProjetosEngenhariaRoute: ProjetosEngenhariaRoute,
  ProjetosProgramacaoRoute: ProjetosProgramacaoRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
